services:
  gateway:
    container_name: gateway
    build:
      context: ../gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: gateway
    depends_on:
      - fluent-bit
      
  fluent-bit:
    image: fluent/fluent-bit:4.0.5
    container_name: fluent-bit
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - loki
  loki:
    image: grafana/loki:3.5.3
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  
